-- Enhanced schema.sql with historical voucher support

-- Core users table for auth
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255) NULL,
  role ENUM('admin', 'viewer') NOT NULL DEFAULT 'viewer',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Active vouchers table (synced with cloud)
CREATE TABLE IF NOT EXISTS vouchers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(255) NOT NULL UNIQUE,
  tenant_id VARCHAR(255) NOT NULL,
  voucher_code VARCHAR(255) NOT NULL,
  name_ref VARCHAR(255) NULL,
  package_name VARCHAR(255) NOT NULL,
  time_period INT NOT NULL COMMENT 'Duration in minutes',
  used_time INT DEFAULT 0 COMMENT 'Used time in minutes',
  create_time BIGINT NOT NULL COMMENT 'Creation timestamp in milliseconds',
  login_time BIGINT NULL COMMENT 'First login timestamp in milliseconds',
  expiry_time BIGINT NULL COMMENT 'Expiry timestamp in milliseconds',
  max_clients INT DEFAULT 1,
  current_clients INT DEFAULT 0,
  quota DECIMAL(10,2) DEFAULT 0 COMMENT 'Data quota in MB',
  used_quota DECIMAL(10,2) DEFAULT 0 COMMENT 'Used quota in MB',
  status VARCHAR(10) NOT NULL DEFAULT '1',
  qrcode_url VARCHAR(500) NULL,
  download_rate_limit INT DEFAULT 0,
  upload_rate_limit INT DEFAULT 0,
  bind_mac TINYINT DEFAULT 0,
  user_group_id VARCHAR(50) NULL,
  user_group_name VARCHAR(255) NULL,
  first_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  phone VARCHAR(50) NULL,
  comment TEXT NULL,
  disable_status TINYINT DEFAULT 0,
  raw_data JSON,
  last_synced TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_package_name (package_name),
  INDEX idx_status (status),
  INDEX idx_uuid (uuid),
  INDEX idx_tenant_id (tenant_id),
  INDEX idx_voucher_code (voucher_code),
  INDEX idx_user_group_id (user_group_id),
  INDEX idx_email (email),
  INDEX idx_phone (phone)
);

-- Historical vouchers table (vouchers that were deleted from cloud but preserved locally)
CREATE TABLE IF NOT EXISTS vouchers_historical (
  id INT AUTO_INCREMENT PRIMARY KEY,
  original_voucher_id INT NULL COMMENT 'Reference to original voucher ID',
  uuid VARCHAR(255) NOT NULL,
  tenant_id VARCHAR(255) NOT NULL,
  voucher_code VARCHAR(255) NOT NULL,
  name_ref VARCHAR(255) NULL,
  package_name VARCHAR(255) NOT NULL,
  time_period INT NOT NULL COMMENT 'Duration in minutes',
  used_time INT DEFAULT 0 COMMENT 'Used time in minutes',
  create_time BIGINT NOT NULL COMMENT 'Creation timestamp in milliseconds',
  login_time BIGINT NULL COMMENT 'First login timestamp in milliseconds',
  expiry_time BIGINT NULL COMMENT 'Expiry timestamp in milliseconds',
  max_clients INT DEFAULT 1,
  current_clients INT DEFAULT 0,
  quota DECIMAL(10,2) DEFAULT 0 COMMENT 'Data quota in MB',
  used_quota DECIMAL(10,2) DEFAULT 0 COMMENT 'Used quota in MB',
  status VARCHAR(10) NOT NULL DEFAULT '1',
  qrcode_url VARCHAR(500) NULL,
  download_rate_limit INT DEFAULT 0,
  upload_rate_limit INT DEFAULT 0,
  bind_mac TINYINT DEFAULT 0,
  user_group_id VARCHAR(50) NULL,
  user_group_name VARCHAR(255) NULL,
  first_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  phone VARCHAR(50) NULL,
  comment TEXT NULL,
  disable_status TINYINT DEFAULT 0,
  raw_data JSON,
  last_synced TIMESTAMP NULL COMMENT 'Last sync when it was active',
  archived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'When moved to historical',
  archived_reason VARCHAR(255) DEFAULT 'removed_from_cloud' COMMENT 'Why it was archived',
  sync_log_id INT NULL COMMENT 'Reference to sync that archived it',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_uuid_historical (uuid),
  INDEX idx_package_name_historical (package_name),
  INDEX idx_voucher_code_historical (voucher_code),
  INDEX idx_archived_at (archived_at),
  INDEX idx_archived_reason (archived_reason),
  INDEX idx_original_voucher_id (original_voucher_id),
  INDEX idx_sync_log_id (sync_log_id)
);

-- Enhanced sync log to track archival operations
CREATE TABLE IF NOT EXISTS voucher_sync_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sync_started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  sync_completed_at TIMESTAMP NULL,
  total_fetched INT DEFAULT 0,
  total_processed INT DEFAULT 0,
  total_new INT DEFAULT 0,
  total_updated INT DEFAULT 0,
  total_archived INT DEFAULT 0 COMMENT 'Vouchers moved to historical',
  status ENUM('running', 'completed', 'failed') DEFAULT 'running',
  error_message TEXT NULL,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Voucher lifecycle tracking (detailed audit trail)
CREATE TABLE IF NOT EXISTS voucher_lifecycle_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  voucher_uuid VARCHAR(255) NOT NULL,
  event_type ENUM('created', 'updated', 'archived', 'restored', 'disabled', 'enabled', 'deleted', 'synced', 'bulk_operation', 'field_updated') NOT NULL,
  event_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  sync_log_id INT NULL,
  old_status VARCHAR(10) NULL,
  new_status VARCHAR(10) NULL,
  notes TEXT NULL,
  details JSON NULL COMMENT 'Additional event details (changed fields, etc)',
  user_id INT NULL,
  INDEX idx_voucher_uuid_events (voucher_uuid),
  INDEX idx_event_type (event_type),
  INDEX idx_event_timestamp (event_timestamp),
  FOREIGN KEY (sync_log_id) REFERENCES voucher_sync_log(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Application settings (key-value store)
CREATE TABLE IF NOT EXISTS app_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  setting_key VARCHAR(255) NOT NULL UNIQUE,
  setting_value TEXT NULL,
  setting_type ENUM('string', 'number', 'boolean', 'json') DEFAULT 'string',
  description TEXT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by INT NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id),
  INDEX idx_setting_key (setting_key)
);

-- View for combined voucher data (active + historical)
CREATE OR REPLACE VIEW vouchers_combined AS
SELECT 
  id,
  uuid,
  tenant_id,
  voucher_code,
  name_ref,
  package_name,
  time_period,
  used_time,
  create_time,
  login_time,
  expiry_time,
  max_clients,
  current_clients,
  quota,
  used_quota,
  status,
  qrcode_url,
  download_rate_limit,
  upload_rate_limit,
  bind_mac,
  user_group_id,
  user_group_name,
  first_name,
  last_name,
  email,
  phone,
  comment,
  disable_status,
  raw_data,
  last_synced,
  created_at,
  'active' as voucher_state,
  NULL as archived_at,
  NULL as archived_reason
FROM vouchers

UNION ALL

SELECT 
  id,
  uuid,
  tenant_id,
  voucher_code,
  name_ref,
  package_name,
  time_period,
  used_time,
  create_time,
  login_time,
  expiry_time,
  max_clients,
  current_clients,
  quota,
  used_quota,
  status,
  qrcode_url,
  download_rate_limit,
  upload_rate_limit,
  bind_mac,
  user_group_id,
  user_group_name,
  first_name,
  last_name,
  email,
  phone,
  comment,
  disable_status,
  raw_data,
  last_synced,
  created_at,
  'historical' as voucher_state,
  archived_at,
  archived_reason
FROM vouchers_historical;